In [ ]:
import pandas as pd

file_path = r"C:\Users\asus M1603\Desktop\Final Project\Data\mastersportal_all.xlsx"
df = pd.read_excel(file_path)

df.head()

,degree_tag,university_name,program_name,review_score,review_count,durations,start_dates,language,language_requirements,delivery_type,credits,campus_location,disciplines,tuition,cost_of_living
0,Master,IÉSEG School of Management,AI and Data Analytics for Business,4.2,60.0,NaN,Starting September 2026 | Apply before Jun 2026,English,Duolingo English Test 115 | TOEFL® IBT 85 | IE...,On Campus,120 ECTS,"Lille, France",Artificial Intelligence | Data Analytics | Vie...,"{""original_amount"": ""23300"", ""original_currenc...","{""amount_min_display"": null, ""amount_max_displ..."
1,M.Sc.,Brunel University of London,Artificial Intelligence,4.0,157.0,Full-time 12 months | Part-time 24 months | to...,Starting January 2026 | Apply before Nov 2025 ...,English,TOEFL® IBT 90 | PTE Academic 59 | IELTS 6.5 | ...,On Campus,180 alternative credits,"London, United Kingdom",Artificial Intelligence | View 306 other Maste...,"{""original_amount"": ""24795"", ""original_currenc...","{""amount_min_display"": null, ""amount_max_displ..."
2,M.Sc.,Brunel University of London,Human-AI Interaction,4.0,157.0,Full-time 12 months,Starting September 2026 | Apply before Jul 2026,English,PTE Academic 59 | IELTS 6.5 | PTE Academic 59 ...,On Campus,180 alternative credits,"London, United Kingdom",Computer Sciences | Human Computer Interaction...,"{""original_amount"": ""24795"", ""original_currenc...","{""amount_min_display"": null, ""amount_max_displ..."
3,M.Sc.,University of Bradford,Applied Artificial Intelligence and Data Analy...,4.4,65.0,Full-time 12 months | tooltip: 12 months (Sept...,Starting January 2026 | Apply before Nov 2025 ...,English,TOEFL® IBT 80 | PTE Academic 62 | IELTS 6 | TO...,On Campus,180 alternative credits,"Bradford, United Kingdom",Artificial Intelligence | Data Analytics | Vie...,"{""original_amount"": ""21490"", ""original_currenc...","{""amount_min_display"": null, ""amount_max_displ..."
4,M.Sc.,Loughborough University,Management and Artificial Intelligence,4.4,54.0,Full-time 12 months,Starting September 2026 | Apply before Sep 2026,English,Duolingo English Test 120 | TOEFL® IBT 92 | PT...,On Campus,180 alternative credits,"London, United Kingdom",Management Studies | Artificial Intelligence |...,"{""original_amount"": ""30900"", ""original_currenc...","{""amount_min_display"": null, ""amount_max_displ..."

In [ ]:
unique_values = (
    pd.Series(df["degree_tag"].dropna().unique())
    .sort_values()
    .reset_index(drop=True)
)

print("Unique degree_tag değerleri:")
print(unique_values)

Benzersiz degree_tag değerleri:
0               Higher Diploma
1                        LL.M.
2                         M.A.
3                       M.B.A.
4                       M.Eng.
5                       M.P.A.
6                      M.Phil.
7                       M.Res.
8                       M.S.S.
9                        M.Sc.
10            M.Sc./P.Grad.Dip
11                      MA/MSc
12                        MASc
13                    MBA/MEng
14                         MBM
15                         MBS
16                         MDS
17                         MIM
18                        MMIR
19                MPhil / MScR
20                   MPhil/PhD
21                         MSD
22                         MSM
23        MSc / PGDip / PGCert
24        MSc / PgDip / PgCert
25         MSc and Engineering
26          MSc, PgDip, PgCert
27              MSc/PDip/PCert
28                 MSc/PG Cert
29          MSc/PG Dip/PG Cert
30            MSc/PGDip/PGCert
31                 MSc/PgD/PgC
32            MSc/PgDip/PgCert
33                     MSc/PhD
34                         MSt
35                      Master
36             Master's Degree
37                        MiBA
38                 PgC/PgD/MSc
39            PgCert/PgDip/MSc
40    Postgraduate Certificate
41        Postgraduate Diploma
42                  Pre-Master
dtype: object

In [4]:
replace_map = {
    # MSc
    'M.Sc.': 'MSc', 'M.Sc./P.Grad.Dip': 'MSc', 'MSc / PGDip / PGCert': 'MSc',
    'MSc / PgDip / PgCert': 'MSc', 'MSc and Engineering': 'MSc',
    'MSc, PgDip, PgCert': 'MSc', 'MSc/PDip/PCert': 'MSc', 'MSc/PG Cert': 'MSc',
    'MSc/PG Dip/PG Cert': 'MSc', 'MSc/PGDip/PGCert': 'MSc', 'MSc/PgD/PgC': 'MSc',
    'MSc/PgDip/PgCert': 'MSc', 'PgC/PgD/MSc': 'MSc', 'PgCert/PgDip/MSc': 'MSc',
    'MA/MSc': 'MSc', 'MBA/MEng': 'MSc',
    # MA
    'M.A.': 'MA', 'Master': 'MA', "Master's Degree": 'MA',
    # MBA
    'M.B.A.': 'MBA', 'MBM': 'MBA', 'MBS': 'MBA', 'MIM': 'MBA', 'MSM': 'MBA', 'MiBA': 'MBA',
    # MEng
    'M.Eng.': 'MEng', 'MASc': 'MEng', 'MDS': 'MEng', 'MPhil / MScR': 'MEng',
    # MPhil
    'M.Phil.': 'MPhil', 'MPhil/PhD': 'MPhil',
    # MRes
    'M.Res.': 'MRes',
    # LLM
    'LL.M.': 'LLM',
    # MPA
    'M.P.A.': 'MPA',
    # MSS
    'M.S.S.': 'MSS',
    # MSt
    'MSt': 'MSt',
    # Pre-Master
    'Higher Diploma': 'Pre-Master', 'Pre-Master': 'Pre-Master',
    # PgDip / PgCert (Postgraduate)
    'Postgraduate Certificate': 'PgCert', 'Postgraduate Diploma': 'PgDip',
}

df['degree_tag_clean'] = df['degree_tag'].replace(replace_map)
df['degree_tag_clean'].value_counts()

degree_tag_clean
MSc           911
MA            195
MBA            45
Pre-Master     36
MEng           16
PgCert         13
MRes            8
LLM             7
PgDip           5
MPhil           4
MPA             2
MSD             1
MMIR            1
MSt             1
MSS             1
MSc/PhD         1
Name: count, dtype: int64

In [5]:
df['review_score'] = df['review_score'].astype(float)
df.loc[df['review_score'] == 4, 'review_score'] = 4.0
df.loc[df['review_score'] == 5, 'review_score'] = 5.0

In [6]:
df['review_count'] = df['review_count'].astype('Int64')

In [8]:
inconsistent_rows = df[
    ((df['review_score'].notna()) & (df['review_count'].isna())) |
    ((df['review_score'].isna()) & (df['review_count'].notna()))
]

print(f"Inconsistent rows: {len(inconsistent_rows)}")
inconsistent_rows[['university_name', 'program_name', 'review_score', 'review_count']].head(20)

Inconsistent rows: 0

Empty DataFrame
Columns: [university_name, program_name, review_score, review_count]
Index: []

In [ ]:
import re
import pandas as pd


pat_ft = re.compile(r'Full-time\s+(\d+)\s+months')
pat_pt = re.compile(r'Part-time\s+(\d+)\s+months')

def to_mode_fields(txt):
    if pd.isna(txt):
        return pd.NA, pd.NA
    s = str(txt)

    modes = []
    months = []


    m_ft = pat_ft.search(s)
    if m_ft:
        modes.append("Full-time")
        months.append(m_ft.group(1))

    m_pt = pat_pt.search(s)
    if m_pt:
        modes.append("Part-time")
        months.append(m_pt.group(1))

    if not modes:
        return pd.NA, pd.NA

    return " | ".join(modes), " | ".join(months)

df[['study_mode', 'study_mode_months']] = df['durations'].apply(
    lambda x: pd.Series(to_mode_fields(x))
)

In [ ]:

df = df[~df['study_mode_months'].astype(str).str.contains("60", na=False)]


if 'durations' in df.columns:
    df = df.drop(columns=['durations'])

In [20]:
if 'degree_tag' in df.columns:
    df = df.drop(columns=['degree_tag'])

In [ ]:
import re
import pandas as pd
import numpy as np

df['start_dates'] = df['start_dates'].astype(str).str.replace("Apply before Deadline", "Apply before", regex=False)

MONTH_MAP = {
    'January':'01','Jan':'01',
    'February':'02','Feb':'02',
    'March':'03','Mar':'03',
    'April':'04','Apr':'04',
    'May':'05',
    'June':'06','Jun':'06',
    'July':'07','Jul':'07',
    'August':'08','Aug':'08',
    'September':'09','Sep':'09',
    'October':'10','Oct':'10',
    'November':'11','Nov':'11',
    'December':'12','Dec':'12'
}

RE_START = re.compile(r'^Starting\s+([A-Za-z]+)\s+(\d{4})$')
RE_APPLY = re.compile(r'^Apply before\s+([A-Za-z]+)\s+(\d{4})$')

def to_mm_yyyy(month_str, year_str):
    mm = MONTH_MAP.get(month_str, None)
    if mm is None:
        return pd.NA
    return f"{mm}.{year_str}"

def split_all_pairs(text):
    """
    - Metni '|' ile böler, sırayla tüm 'Starting' ve 'Apply before' bölümlerini toplar.
    - 'Starting'ler intake listesine, 'Apply before'lar deadline listesine eklenir.
    - Apply sayısı Starting sayısından fazlaysa Starting sayısına kadar sınırlandırılır.
    - Çıktı iki metin: "MM.YYYY | MM.YYYY ..." biçiminde.
    """
    if pd.isna(text) or str(text).strip() == "" or text == "nan":
        return pd.NA, pd.NA

    parts = [p.strip() for p in str(text).split('|') if p.strip()]

    intake_list = []
    deadline_list = []

    for p in parts:
        ms = RE_START.match(p)
        if ms:
            intake_list.append(to_mm_yyyy(ms.group(1), ms.group(2)))
            continue
        ma = RE_APPLY.match(p)
        if ma:
            deadline_list.append(to_mm_yyyy(ma.group(1), ma.group(2)))
            continue

    if len(deadline_list) > len(intake_list):
        deadline_list = deadline_list[:len(intake_list)]

    intake_val = " | ".join([x for x in intake_list if pd.notna(x)]) if any(pd.notna(x) for x in intake_list) else pd.NA
    deadline_val = " | ".join([x for x in deadline_list if pd.notna(x)]) if any(pd.notna(x) for x in deadline_list) else pd.NA

    return intake_val, deadline_val

df[['intake_month', 'application_deadline_month']] = df['start_dates'].apply(
    lambda x: pd.Series(split_all_pairs(x), index=['intake_month', 'application_deadline_month'])
)

In [27]:
if 'start_dates' in df.columns:
    df = df.drop(columns=['start_dates'])

In [ ]:
import pandas as pd
import re
import unicodedata

LANG_MAP = {
    'english': 'English',
    'german': 'German',
    'russian': 'Russian',
    'spanish': 'Spanish',
    'french': 'French',
    'italian': 'Italian',
}


LANG_PATTERN = re.compile(r'\b(english|german|russian|spanish|french|italian)\b', flags=re.IGNORECASE)

def normalize_text(s):
    if pd.isna(s):
        return s
    s = unicodedata.normalize('NFKC', str(s)).strip()
    s = re.sub(r'\s+', ' ', s)
    return s

def clean_language_value(text):
    if pd.isna(text):
        return pd.NA
    s = normalize_text(text)

    found = []
    for m in LANG_PATTERN.finditer(s):
        k = m.group(1).lower()
        if k not in found:
            found.append(k)

    if not found:
        return pd.NA

    found = found[:2]
    return " | ".join(LANG_MAP[k] for k in found)

df['language_clean'] = df['language'].apply(clean_language_value)

In [36]:
if 'language' in df.columns:
    df = df.drop(columns=['language'])

In [ ]:
def clean_lang(text):
    if pd.isna(text):
        return ""
    s = str(text).strip()
    low = s.lower()

    out_parts = []

    def find_with_number(patterns):
        for pat in patterns:
            m = re.search(pat, low, flags=re.I)
            if m:
                num = m.group(m.lastindex) if m.lastindex else None
                if num:
                    return num.strip()
        return None

    # IELTS
    ielts_num = find_with_number([r"\bielts[^0-9]{0,15}(\d+(?:\.\d+)?)"])
    if ielts_num:
        out_parts.append(f"IELTS {ielts_num}")

    # TOEFL® IBT
    toefl_num = find_with_number([
        r"\btoefl\s*(?:i\s*bt|ibt|i-?bt)?[^0-9]{0,15}(\d+(?:\.\d+)?)",
        r"\bibt[^0-9]{0,15}(\d+(?:\.\d+)?)"
    ])
    if toefl_num:
        out_parts.append(f"TOEFL® IBT {toefl_num}")

    # PTE Academic
    pte_num = find_with_number([r"\bpte(?:\s*academic|\s*acad\.?)?[^0-9]{0,15}(\d+(?:\.\d+)?)"])
    if pte_num:
        out_parts.append(f"PTE Academic {pte_num}")

    # Duolingo English Test
    det_num = find_with_number([
        r"\bduolingo(?:\s*english\s*test)?[^0-9]{0,15}(\d+(?:\.\d+)?)",
        r"\bdet[^0-9]{0,15}(\d+(?:\.\d+)?)"
    ])
    if det_num:
        out_parts.append(f"Duolingo English Test {det_num}")

    # OTE
    ote_num = find_with_number([
        r"\boxford\s*test\s*of\s*english[^0-9]{0,15}(\d+(?:\.\d+)?)",
        r"\bote[^0-9]{0,15}(\d+(?:\.\d+)?)"
    ])
    if ote_num:
        out_parts.append(f"OTE {ote_num}")

    return " | ".join(out_parts).strip()

df["language_requirements_std"] = df["language_requirements"].apply(clean_lang)


print(df[["language_requirements", "language_requirements_std"]].head(12).to_string(index=False))

                                      language_requirements                                   language_requirements_std
      IELTS 6.5 | TOEFL® IBT 85 | Duolingo English Test 115       IELTS 6.5 | TOEFL® IBT 85 | Duolingo English Test 115
                IELTS 6.5 | TOEFL® IBT 90 | PTE Academic 59                 IELTS 6.5 | TOEFL® IBT 90 | PTE Academic 59
                                IELTS 6.5 | PTE Academic 59                                 IELTS 6.5 | PTE Academic 59
                  IELTS 6 | TOEFL® IBT 80 | PTE Academic 62                   IELTS 6 | TOEFL® IBT 80 | PTE Academic 62
TOEFL® IBT 92 | PTE Academic 67 | Duolingo English Test 120 TOEFL® IBT 92 | PTE Academic 67 | Duolingo English Test 120
                                                        NaN
                IELTS 6.5 | TOEFL® IBT 92 | PTE Academic 71                 IELTS 6.5 | TOEFL® IBT 92 | PTE Academic 71
                                  IELTS 6.5 | TOEFL® IBT 79                                   IELTS 6.5 | TOEFL® IBT 79
                                    IELTS 6 | TOEFL® IBT 79                                     IELTS 6 | TOEFL® IBT 79
                                                  IELTS 6.5                                                   IELTS 6.5
                                  IELTS 6.5 | TOEFL® IBT 90                                   IELTS 6.5 | TOEFL® IBT 90
                  IELTS 6 | TOEFL® IBT 60 | PTE Academic 59                   IELTS 6 | TOEFL® IBT 60 | PTE Academic 59

In [ ]:
def clean_delivery_type(text):
    if pd.isna(text):
        return ""
    s = str(text).lower().strip()

    oncampus = bool(re.search(r"\bon\s*campus\b", s))
    blended = bool(re.search(r"\bblended\b", s))
    online = bool(re.search(r"\bonline\b", s))

    parts = []
    if oncampus:
        parts.append("On Campus")
    if blended:
        parts.append("Blended")
    if online:
        parts.append("Online")

    return " | ".join(parts)

df["delivery_type_std"] = df["delivery_type"].apply(clean_delivery_type)

print(df[["delivery_type", "delivery_type_std"]].head(12).to_string(index=False))

delivery_type delivery_type_std
    On Campus         On Campus
    On Campus         On Campus
    On Campus         On Campus
    On Campus         On Campus
    On Campus         On Campus
    On Campus         On Campus
    On Campus         On Campus
    On Campus         On Campus
    On Campus         On Campus
       Online            Online
    On Campus         On Campus
    On Campus         On Campus

In [ ]:
if 'delivery_type' in df.columns:
    df = df.drop(columns=['delivery_type'])

In [ ]:
# 1. SCH olan satırları sil
df = df[~df["credits"].str.contains("SCH", case=False, na=False)].copy()


def convert_to_ects(cell):
    if pd.isna(cell):
        return cell
    s = str(cell).strip().lower()
    m = re.search(r"(\d+(?:\.\d+)?)", s)
    if not m:
        return None
    val = float(m.group(1))
    if "ects" in s:
        return val
    elif "alternative" in s:
        return round(val / 2, 0)
    else:
        return None

df["credits_ects"] = df["credits"].apply(convert_to_ects)

print(df[["credits", "credits_ects"]].head(20).to_string(index=False))

                credits  credits_ects
               120 ECTS         120.0
180 alternative credits          90.0
180 alternative credits          90.0
180 alternative credits          90.0
180 alternative credits          90.0
                60 ECTS          60.0
180 alternative credits          90.0
               120 ECTS         120.0
180 alternative credits          90.0
180 alternative credits          90.0
               120 ECTS         120.0
180 alternative credits          90.0
180 alternative credits          90.0
180 alternative credits          90.0
               120 ECTS         120.0
120 alternative credits          60.0
180 alternative credits          90.0
               120 ECTS         120.0
180 alternative credits          90.0
180 alternative credits          90.0

In [62]:
if 'credits' in df.columns:
    df = df.drop(columns=['credits'])

In [ ]:
df[["city", "country"]] = df["campus_location"].str.split(",", n=1, expand=True)

df["city"] = df["city"].str.strip()
df["country"] = df["country"].str.strip()

print(df[["campus_location", "city", "country"]].head(20).to_string(index=False))

            campus_location        city        country
              Lille, France       Lille         France
     London, United Kingdom      London United Kingdom
     London, United Kingdom      London United Kingdom
   Bradford, United Kingdom    Bradford United Kingdom
     London, United Kingdom      London United Kingdom
           Lisbon, Portugal      Lisbon       Portugal
     London, United Kingdom      London United Kingdom
          Brussels, Belgium    Brussels        Belgium
 Portsmouth, United Kingdom  Portsmouth United Kingdom
 Abbey Wood, United Kingdom  Abbey Wood United Kingdom
     Eindhoven, Netherlands   Eindhoven    Netherlands
Bournemouth, United Kingdom Bournemouth United Kingdom
     London, United Kingdom      London United Kingdom
 Abbey Wood, United Kingdom  Abbey Wood United Kingdom
     Eindhoven, Netherlands   Eindhoven    Netherlands
     Bangor, United Kingdom      Bangor United Kingdom
     London, United Kingdom      London United Kingdom
            Berlin, Germany      Berlin        Germany
     London, United Kingdom      London United Kingdom
    Chatham, United Kingdom     Chatham United Kingdom

In [64]:
if 'campus_location' in df.columns:
    df = df.drop(columns=['campus_location'])

In [ ]:
def clean_disciplines(cell):
    if pd.isna(cell):
        return ""
    s = str(cell).strip()

    s = re.sub(r"\|?\s*View.*", "", s, flags=re.I).strip()

    parts = [p.strip() for p in s.split("|") if p.strip()]

    seen = set()
    unique_parts = []
    for p in parts:
        if p not in seen:
            seen.add(p)
            unique_parts.append(p)

    return " | ".join(unique_parts)


df["disciplines_clean"] = df["disciplines"].apply(clean_disciplines)


print(df[["disciplines", "disciplines_clean"]].head(15).to_string(index=False))

                                                                                                                                   disciplines                                                        disciplines_clean
                                         Artificial Intelligence | Data Analytics | View 53 other Masters in Artificial Intelligence in France                                 Artificial Intelligence | Data Analytics
                                                 Artificial Intelligence | View 306 other Masters in Artificial Intelligence in United Kingdom                                                  Artificial Intelligence
Computer Sciences | Human Computer Interaction | Artificial Intelligence | View 306 other Masters in Artificial Intelligence in United Kingdom Computer Sciences | Human Computer Interaction | Artificial Intelligence
                                Artificial Intelligence | Data Analytics | View 306 other Masters in Artificial Intelligence in United Kingdom                                 Artificial Intelligence | Data Analytics
                            Management Studies | Artificial Intelligence | View 306 other Masters in Artificial Intelligence in United Kingdom                             Management Studies | Artificial Intelligence
                              Business Administration | Artificial Intelligence | View 17 other Masters in Business Administration in Portugal                        Business Administration | Artificial Intelligence
                                                 Artificial Intelligence | View 306 other Masters in Artificial Intelligence in United Kingdom                                                  Artificial Intelligence
               Computer Sciences | Software Engineering | Artificial Intelligence | View 8 other Masters in Artificial Intelligence in Belgium       Computer Sciences | Software Engineering | Artificial Intelligence
                              Artificial Intelligence | Machine Learning | View 306 other Masters in Artificial Intelligence in United Kingdom                               Artificial Intelligence | Machine Learning
                Data Science & Big Data | Artificial Intelligence | Data Analytics | View 35 other Masters in Data Analytics in United Kingdom       Data Science & Big Data | Artificial Intelligence | Data Analytics
                           Data Science & Big Data | Artificial Intelligence | View 40 other Masters in Artificial Intelligence in Netherlands                        Data Science & Big Data | Artificial Intelligence
                       Data Science & Big Data | Artificial Intelligence | View 306 other Masters in Artificial Intelligence in United Kingdom                        Data Science & Big Data | Artificial Intelligence
                                   Sports Management | Artificial Intelligence | View 128 other Masters in Sports Management in United Kingdom                              Sports Management | Artificial Intelligence
                                    Robotics | Artificial Intelligence | Machine Learning | View 5 other Masters in Robotics in United Kingdom                    Robotics | Artificial Intelligence | Machine Learning
                  General Engineering & Technology | Artificial Intelligence | View 40 other Masters in Artificial Intelligence in Netherlands               General Engineering & Technology | Artificial Intelligence

In [66]:
if 'disciplines' in df.columns:
    df = df.drop(columns=['disciplines'])

In [69]:
amt_pat = re.compile(r'"original_amount"\s*:\s*"(?P<amt>\d+(?:\.\d+)?)"')
cur_pat = re.compile(r'"original_currency"\s*:\s*"(?P<cur>[A-Z]{3})"')

def extract_tuition_regex(cell):
    if pd.isna(cell):
        return pd.Series({"tuition_amount": None, "tuition_currency": None})
    s = str(cell)
    m_amt = amt_pat.search(s)
    m_cur = cur_pat.search(s)
    amt = float(m_amt.group("amt")) if m_amt else None
    cur = m_cur.group("cur") if m_cur else None
    return pd.Series({"tuition_amount": amt, "tuition_currency": cur})

tuition_info = df["tuition"].apply(extract_tuition_regex)
df = pd.concat([df, tuition_info], axis=1)

print(df[["tuition", "tuition_amount", "tuition_currency"]].head(15).to_string(index=False))

                                                                                                                             tuition  tuition_amount  tuition_amount tuition_currency tuition_currency
{"original_amount": "23300", "original_currency": "EUR", "display_amount": null, "display_currency": null, "display_duration": null}            None         23300.0             None              EUR
{"original_amount": "24795", "original_currency": "GBP", "display_amount": null, "display_currency": null, "display_duration": null}            None         24795.0             None              GBP
{"original_amount": "24795", "original_currency": "GBP", "display_amount": null, "display_currency": null, "display_duration": null}            None         24795.0             None              GBP
{"original_amount": "21490", "original_currency": "GBP", "display_amount": null, "display_currency": null, "display_duration": null}            None         21490.0             None              GBP
{"original_amount": "30900", "original_currency": "GBP", "display_amount": null, "display_currency": null, "display_duration": null}            None         30900.0             None              GBP
 {"original_amount": "4900", "original_currency": "EUR", "display_amount": null, "display_currency": null, "display_duration": null}            None          4900.0             None              EUR
{"original_amount": "33500", "original_currency": "GBP", "display_amount": null, "display_currency": null, "display_duration": null}            None         33500.0             None              GBP
 {"original_amount": "5320", "original_currency": "EUR", "display_amount": null, "display_currency": null, "display_duration": null}            None          5320.0             None              EUR
{"original_amount": "19200", "original_currency": "GBP", "display_amount": null, "display_currency": null, "display_duration": null}            None         19200.0             None              GBP
{"original_amount": "17357", "original_currency": "GBP", "display_amount": null, "display_currency": null, "display_duration": null}            None         17357.0             None              GBP
{"original_amount": "21000", "original_currency": "EUR", "display_amount": null, "display_currency": null, "display_duration": null}            None         21000.0             None              EUR
{"original_amount": "18750", "original_currency": "GBP", "display_amount": null, "display_currency": null, "display_duration": null}            None         18750.0             None              GBP
{"original_amount": "30900", "original_currency": "GBP", "display_amount": null, "display_currency": null, "display_duration": null}            None         30900.0             None              GBP
{"original_amount": "17357", "original_currency": "GBP", "display_amount": null, "display_currency": null, "display_duration": null}            None         17357.0             None              GBP
{"original_amount": "21000", "original_currency": "EUR", "display_amount": null, "display_currency": null, "display_duration": null}            None         21000.0             None              EUR

In [ ]:
df.columns = [c.lower() for c in df.columns]

df = df.loc[:, ~df.columns.duplicated(keep='last')]

df = df.dropna(axis=1, how='all')

df.head()

['university_name', 'program_name', 'review_score', 'review_count', 'tuition', 'cost_of_living', 'degree_tag_clean', 'study_mode', 'study_mode_months', 'intake_month', 'application_deadline_month', 'language_clean', 'language_requirements_std', 'delivery_type_std', 'credits_ects', 'city', 'country', 'disciplines_clean', 'tuition_amount', 'tuition_currency']

,university_name,program_name,review_score,review_count,tuition,cost_of_living,degree_tag_clean,study_mode,study_mode_months,intake_month,application_deadline_month,language_clean,language_requirements_std,delivery_type_std,credits_ects,city,country,disciplines_clean,tuition_amount,tuition_currency
0,IÉSEG School of Management,AI and Data Analytics for Business,4.2,60.0,"{""original_amount"": ""23300"", ""original_currenc...","{""amount_min_display"": null, ""amount_max_displ...",MA,NaN,NaN,09.2026,06.2026,English,IELTS 6.5 | TOEFL® IBT 85 | Duolingo English T...,On Campus,120.0,Lille,France,Artificial Intelligence | Data Analytics,23300.0,EUR
1,Brunel University of London,Artificial Intelligence,4.0,157.0,"{""original_amount"": ""24795"", ""original_currenc...","{""amount_min_display"": null, ""amount_max_displ...",MSc,Full-time | Part-time,12 | 24,01.2026 | 09.2026,11.2025 | 07.2026,English,IELTS 6.5 | TOEFL® IBT 90 | PTE Academic 59,On Campus,90.0,London,United Kingdom,Artificial Intelligence,24795.0,GBP
2,Brunel University of London,Human-AI Interaction,4.0,157.0,"{""original_amount"": ""24795"", ""original_currenc...","{""amount_min_display"": null, ""amount_max_displ...",MSc,Full-time,12,09.2026,07.2026,English,IELTS 6.5 | PTE Academic 59,On Campus,90.0,London,United Kingdom,Computer Sciences | Human Computer Interaction...,24795.0,GBP
3,University of Bradford,Applied Artificial Intelligence and Data Analy...,4.4,65.0,"{""original_amount"": ""21490"", ""original_currenc...","{""amount_min_display"": null, ""amount_max_displ...",MSc,Full-time | Part-time,12 | 24,01.2026 | 09.2026,11.2025 | 08.2026,English,IELTS 6 | TOEFL® IBT 80 | PTE Academic 62,On Campus,90.0,Bradford,United Kingdom,Artificial Intelligence | Data Analytics,21490.0,GBP
4,Loughborough University,Management and Artificial Intelligence,4.4,54.0,"{""original_amount"": ""30900"", ""original_currenc...","{""amount_min_display"": null, ""amount_max_displ...",MSc,Full-time,12,09.2026,09.2026,English,TOEFL® IBT 92 | PTE Academic 67 | Duolingo Eng...,On Campus,90.0,London,United Kingdom,Management Studies | Artificial Intelligence,30900.0,GBP

In [73]:
if 'tuition' in df.columns:
    df = df.drop(columns=['tuition'])

In [75]:
exchange_rates = {
    "EUR": 1.0,
    "GBP": 1.17,   # İngiliz Sterlini
    "USD": 0.87,   # ABD Doları
    "CHF": 0.93,   # İsviçre Frangı
    "SEK": 0.088,  # İsveç Kronu
    "NOK": 0.085,  # Norveç Kronu
    "DKK": 0.133,  # Danimarka Kronu
    "PLN": 0.23,   # Polonya Zlotisi
    "CZK": 0.042,  # Çek Korunası
    "HUF": 0.0025, # Macar Forinti
    "RON": 0.20,   # Romen Leyi
    "RUB": 0.011,  # Rus Rublesi
    "TRY": 0.02,   # Türk Lirası
    "ISK": 0.0069  # İzlanda Kronası
}

def convert_to_eur(row):
    amt = row.get("tuition_amount")
    cur = row.get("tuition_currency")
    if pd.isna(amt) or cur not in exchange_rates:
        return None
    return round(amt * exchange_rates[cur], 2)

df["tuition_amount_eur"] = df.apply(convert_to_eur, axis=1)

print(df[["tuition_amount", "tuition_currency", "tuition_amount_eur"]].head(15).to_string(index=False))

 tuition_amount tuition_currency  tuition_amount_eur
        23300.0              EUR            23300.00
        24795.0              GBP            29010.15
        24795.0              GBP            29010.15
        21490.0              GBP            25143.30
        30900.0              GBP            36153.00
         4900.0              EUR             4900.00
        33500.0              GBP            39195.00
         5320.0              EUR             5320.00
        19200.0              GBP            22464.00
        17357.0              GBP            20307.69
        21000.0              EUR            21000.00
        18750.0              GBP            21937.50
        30900.0              GBP            36153.00
        17357.0              GBP            20307.69
        21000.0              EUR            21000.00

In [77]:
min_pat = re.compile(r'"amount_min_base"\s*:\s*"(?P<min>\d+(?:\.\d+)?)"')
max_pat = re.compile(r'"amount_max_base"\s*:\s*"(?P<max>\d+(?:\.\d+)?)"')
cur_pat = re.compile(r'"base_currency"\s*:\s*"(?P<cur>[A-Z]{3})"')

def extract_living_info(cell):
    if pd.isna(cell):
        return pd.Series({"living_cost_min": None, "living_cost_max": None, "living_cost_currency": None})
    s = str(cell)
    m_min = min_pat.search(s)
    m_max = max_pat.search(s)
    m_cur = cur_pat.search(s)
    min_val = float(m_min.group("min")) if m_min else None
    max_val = float(m_max.group("max")) if m_max else None
    cur_val = m_cur.group("cur") if m_cur else None
    return pd.Series({"living_cost_min": min_val, "living_cost_max": max_val, "living_cost_currency": cur_val})


living_info = df["cost_of_living"].apply(extract_living_info)
df = pd.concat([df, living_info], axis=1)


print(df[["cost_of_living", "living_cost_min", "living_cost_max", "living_cost_currency"]].head(15).to_string(index=False))

                                                                                                                                                  cost_of_living  living_cost_min  living_cost_max living_cost_currency
 {"amount_min_display": null, "amount_max_display": null, "base_currency": "EUR", "amount_min_base": "741", "amount_max_base": "1145", "display_currency": null}            741.0           1145.0                  EUR
{"amount_min_display": null, "amount_max_display": null, "base_currency": "GBP", "amount_min_base": "1137", "amount_max_base": "2157", "display_currency": null}           1137.0           2157.0                  GBP
{"amount_min_display": null, "amount_max_display": null, "base_currency": "GBP", "amount_min_base": "1137", "amount_max_base": "2157", "display_currency": null}           1137.0           2157.0                  GBP
 {"amount_min_display": null, "amount_max_display": null, "base_currency": "GBP", "amount_min_base": "713", "amount_max_base": "1353", "display_currency": null}            713.0           1353.0                  GBP
{"amount_min_display": null, "amount_max_display": null, "base_currency": "GBP", "amount_min_base": "1137", "amount_max_base": "2157", "display_currency": null}           1137.0           2157.0                  GBP
 {"amount_min_display": null, "amount_max_display": null, "base_currency": "EUR", "amount_min_base": "630", "amount_max_base": "1123", "display_currency": null}            630.0           1123.0                  EUR
{"amount_min_display": null, "amount_max_display": null, "base_currency": "GBP", "amount_min_base": "1137", "amount_max_base": "2157", "display_currency": null}           1137.0           2157.0                  GBP
 {"amount_min_display": null, "amount_max_display": null, "base_currency": "EUR", "amount_min_base": "885", "amount_max_base": "1305", "display_currency": null}            885.0           1305.0                  EUR
 {"amount_min_display": null, "amount_max_display": null, "base_currency": "GBP", "amount_min_base": "710", "amount_max_base": "1099", "display_currency": null}            710.0           1099.0                  GBP
     {"amount_min_display": null, "amount_max_display": null, "base_currency": null, "amount_min_base": null, "amount_max_base": null, "display_currency": null}              NaN              NaN                 None
 {"amount_min_display": null, "amount_max_display": null, "base_currency": "EUR", "amount_min_base": "850", "amount_max_base": "1350", "display_currency": null}            850.0           1350.0                  EUR
 {"amount_min_display": null, "amount_max_display": null, "base_currency": "GBP", "amount_min_base": "700", "amount_max_base": "1000", "display_currency": null}            700.0           1000.0                  GBP
{"amount_min_display": null, "amount_max_display": null, "base_currency": "GBP", "amount_min_base": "1137", "amount_max_base": "2157", "display_currency": null}           1137.0           2157.0                  GBP
     {"amount_min_display": null, "amount_max_display": null, "base_currency": null, "amount_min_base": null, "amount_max_base": null, "display_currency": null}              NaN              NaN                 None
 {"amount_min_display": null, "amount_max_display": null, "base_currency": "EUR", "amount_min_base": "850", "amount_max_base": "1350", "display_currency": null}            850.0           1350.0                  EUR

In [78]:
exchange_rates = {
    "EUR": 1.0,
    "GBP": 1.17,
    "USD": 0.87,
    "CHF": 0.93,
    "SEK": 0.088,
    "NOK": 0.085,
    "DKK": 0.133,
    "PLN": 0.23,
    "CZK": 0.042,
    "HUF": 0.0025,
    "RON": 0.20,
    "RUB": 0.011,
    "TRY": 0.02,
    "ISK": 0.0069,
    "HRK": 0.13,
    "UAH": 0.022
}

df["living_cost_avg"] = df[["living_cost_min", "living_cost_max"]].mean(axis=1)

def convert_living_to_eur(row):
    amt = row.get("living_cost_avg")
    cur = row.get("living_cost_currency")
    if pd.isna(amt) or cur not in exchange_rates:
        return None
    return round(amt * exchange_rates[cur], 2)

df["living_cost_eur"] = df.apply(convert_living_to_eur, axis=1)

print(df[["living_cost_min", "living_cost_max", "living_cost_avg", "living_cost_currency", "living_cost_eur"]].head(15).to_string(index=False))

 living_cost_min  living_cost_max  living_cost_avg living_cost_currency  living_cost_eur
           741.0           1145.0            943.0                  EUR           943.00
          1137.0           2157.0           1647.0                  GBP          1926.99
          1137.0           2157.0           1647.0                  GBP          1926.99
           713.0           1353.0           1033.0                  GBP          1208.61
          1137.0           2157.0           1647.0                  GBP          1926.99
           630.0           1123.0            876.5                  EUR           876.50
          1137.0           2157.0           1647.0                  GBP          1926.99
           885.0           1305.0           1095.0                  EUR          1095.00
           710.0           1099.0            904.5                  GBP          1058.26
             NaN              NaN              NaN                 None              NaN
           850.0           1350.0           1100.0                  EUR          1100.00
           700.0           1000.0            850.0                  GBP           994.50
          1137.0           2157.0           1647.0                  GBP          1926.99
             NaN              NaN              NaN                 None              NaN
           850.0           1350.0           1100.0                  EUR          1100.00

In [81]:
df.head()

,university_name,program_name,review_score,review_count,degree_tag_clean,study_mode,study_mode_months,intake_month,application_deadline_month,language_clean,...,country,disciplines_clean,tuition_amount,tuition_currency,tuition_amount_eur,living_cost_min,living_cost_max,living_cost_currency,living_cost_avg,living_cost_eur
0,IÉSEG School of Management,AI and Data Analytics for Business,4.2,60.0,MA,NaN,NaN,09.2026,06.2026,English,...,France,Artificial Intelligence | Data Analytics,23300.0,EUR,23300.00,741.0,1145.0,EUR,943.0,943.00
1,Brunel University of London,Artificial Intelligence,4.0,157.0,MSc,Full-time | Part-time,12 | 24,01.2026 | 09.2026,11.2025 | 07.2026,English,...,United Kingdom,Artificial Intelligence,24795.0,GBP,29010.15,1137.0,2157.0,GBP,1647.0,1926.99
2,Brunel University of London,Human-AI Interaction,4.0,157.0,MSc,Full-time,12,09.2026,07.2026,English,...,United Kingdom,Computer Sciences | Human Computer Interaction...,24795.0,GBP,29010.15,1137.0,2157.0,GBP,1647.0,1926.99
3,University of Bradford,Applied Artificial Intelligence and Data Analy...,4.4,65.0,MSc,Full-time | Part-time,12 | 24,01.2026 | 09.2026,11.2025 | 08.2026,English,...,United Kingdom,Artificial Intelligence | Data Analytics,21490.0,GBP,25143.30,713.0,1353.0,GBP,1033.0,1208.61
4,Loughborough University,Management and Artificial Intelligence,4.4,54.0,MSc,Full-time,12,09.2026,09.2026,English,...,United Kingdom,Management Studies | Artificial Intelligence,30900.0,GBP,36153.00,1137.0,2157.0,GBP,1647.0,1926.99

In [80]:
if 'cost_of_living' in df.columns:
    df = df.drop(columns=['cost_of_living'])

In [82]:

df.to_excel("master_programs.xlsx", index=False)